[build]
  base    = "client"         # ← client 폴더는 이 경로에 있습니다
  publish = "dist"
  command = "npm run build"  # 실제 배포 전 build 용

[functions]
  directory = "../netlify/functions"

# 가장 구체적인 경로부터 배치합니다
# 1. 특정 ID 패턴 (24자리 16진수)에 대한 리디렉션
[[redirects]]
  from = "/clusters/hot/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-hot-id/:id"
  status = 200
  force = true

[[redirects]]
  from = "/clusters/latest/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-latest-id/:id"
  status = 200
  force = true

# 2. 카테고리 패턴에 대한 리디렉션
[[redirects]]
  from = "/clusters/hot/:category"
  to = "/.netlify/functions/clusters-hot-category/:category"
  status = 200
  force = true

[[redirects]]
  from = "/clusters/latest/:category"
  to = "/.netlify/functions/clusters-latest-category/:category"
  status = 200
  force = true

# 3. 기본 API 엔드포인트
[[redirects]]
  from = "/clusters/hot"
  to = "/.netlify/functions/clusters-hot"
  status = 200

[[redirects]]
  from = "/clusters/latest"
  to = "/.netlify/functions/clusters-latest"
  status = 200

# 4. 통계 API
[[redirects]]
  from = "/api/statistics"
  to = "/.netlify/functions/statistics"
  status = 200

# 5. additional.js 파일이 처리하는 API 경로들
[[redirects]]
  from = "/api/dates"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "dates"

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "categories"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "search"

[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "trending"

# 6. 일반적인 API 리디렉션 (다른 경로에 대한 폴백)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 7. SPA를 위한 리디렉션
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
