[build]
  base    = "client"         # ← client 폴더는 이 경로에 있습니다
  publish = "dist"
  command = "npm run build"  # 실제 배포 전 build 용

[functions]
  directory = "../netlify/functions"

# ID는 일반적으로 24자리 16진수이며, 카테고리는 그렇지 않습니다.
# ID 패턴에 대한 리디렉션을 먼저 정의합니다.
[[redirects]]
  from = "/api/clusters/hot/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-hot-id"
  status = 200
  force = true
  [redirects.query]
    id = ":id"

[[redirects]]
  from = "/api/clusters/latest/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-latest-id"
  status = 200
  force = true
  [redirects.query]
    id = ":id"

# 카테고리 리디렉션을 그 다음에 정의합니다.
[[redirects]]
  from = "/api/clusters/hot/:category"
  to = "/.netlify/functions/clusters-hot-category"
  status = 200
  force = true
  [redirects.query]
    category = ":category"

[[redirects]]
  from = "/api/clusters/latest/:category"
  to = "/.netlify/functions/clusters-latest-category"
  status = 200
  force = true
  [redirects.query]
    category = ":category"

# 기본 API 엔드포인트
[[redirects]]
  from = "/api/clusters/hot"
  to = "/.netlify/functions/clusters-hot"
  status = 200

[[redirects]]
  from = "/api/clusters/latest"
  to = "/.netlify/functions/clusters-latest"
  status = 200

# 일반적인 API 리디렉션 (다른 경로에 대한 폴백)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA를 위한 리디렉션
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
