[build]
  base    = "."             # ← 프로젝트 루트 디렉토리 사용
  publish = "client/dist"   # ← client/dist로 경로 수정
  command = "cd client && npm install && npm run build"  # ← client 디렉토리에서 빌드

[functions]
  directory = "netlify/functions"  # ← 상대 경로 수정

# 가장 구체적인 경로부터 배치합니다
# 1. 특정 ID 패턴 (24자리 16진수)에 대한 리디렉션
[[redirects]]
  from = "/clusters/hot/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-hot-id/:id"
  status = 200
  force = true

[[redirects]]
  from = "/clusters/latest/:id(^[0-9a-fA-F]{24}$)"
  to = "/.netlify/functions/clusters-latest-id/:id"
  status = 200
  force = true

# 2. 카테고리 패턴에 대한 리디렉션
[[redirects]]
  from = "/clusters/hot/:category"
  to = "/.netlify/functions/clusters-hot-category/:category"
  status = 200
  force = true

[[redirects]]
  from = "/clusters/latest/:category"
  to = "/.netlify/functions/clusters-latest-category/:category"
  status = 200
  force = true

# 3. 기본 API 엔드포인트
[[redirects]]
  from = "/clusters/hot"
  to = "/.netlify/functions/clusters-hot"
  status = 200

[[redirects]]
  from = "/clusters/latest"
  to = "/.netlify/functions/clusters-latest"
  status = 200

# 4. 통계 API
[[redirects]]
  from = "/api/statistics"
  to = "/.netlify/functions/statistics"
  status = 200

# 5. 이미지 API 리디렉션
[[redirects]]
  from = "/api/images/:id"
  to = "/.netlify/functions/images/:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/article/:id"
  to = "/.netlify/functions/images/:id"
  status = 200
  force = true
  [redirects.query]
    article = "true"

# 6. additional.js 파일이 처리하는 API 경로들
[[redirects]]
  from = "/api/dates"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "dates"

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "categories"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "search"

[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/additional"
  status = 200
  [redirects.query]
    path = "trending"

# 7. 일반적인 API 리디렉션 (다른 경로에 대한 폴백)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 8. SPA를 위한 리디렉션
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200